/**
 * Ad Templates for RetailSync AI
 * Pre-built templates for Tesco retail media ads
 */

export interface AdTemplate {
  id: string;
  name: string;
  category: 'promotion' | 'product' | 'seasonal' | 'clubcard' | 'awareness';
  description: string;
  thumbnail?: string;
  width: number;
  height: number;
  canvasJSON: object;
}

// Tesco Brand Colors
const TESCO_BLUE = '#00539f';
const TESCO_RED = '#e4002b';
const WHITE = '#ffffff';
const BLACK = '#000000';
const LIGHT_GRAY = '#f5f5f5';

// Template Canvas Data
export const adTemplates: AdTemplate[] = [
  {
    id: 'product-showcase-leaderboard',
    name: 'Product Showcase',
    category: 'product',
    description: 'Highlight a single product with clear pricing',
    width: 728,
    height: 90,
    canvasJSON: {
      version: '6.0.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 728,
          height: 90,
          fill: WHITE,
          selectable: false,
          evented: false,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 90,
          height: 90,
          fill: TESCO_BLUE,
        },
        {
          type: 'i-text',
          left: 110,
          top: 15,
          text: 'SPECIAL OFFER',
          fontSize: 14,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: TESCO_RED,
        },
        {
          type: 'i-text',
          left: 110,
          top: 35,
          text: 'Product Name Here',
          fontSize: 24,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: BLACK,
        },
        {
          type: 'i-text',
          left: 110,
          top: 65,
          text: 'Great value for your family',
          fontSize: 12,
          fontFamily: 'Poppins',
          fill: '#666666',
        },
        {
          type: 'rect',
          left: 580,
          top: 25,
          width: 130,
          height: 40,
          fill: TESCO_RED,
          rx: 20,
          ry: 20,
        },
        {
          type: 'i-text',
          left: 605,
          top: 35,
          text: 'Shop Now',
          fontSize: 14,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: WHITE,
        },
      ],
      background: WHITE,
    },
  },
  {
    id: 'sale-banner-leaderboard',
    name: 'Sale Banner',
    category: 'promotion',
    description: 'Eye-catching sale announcement',
    width: 728,
    height: 90,
    canvasJSON: {
      version: '6.0.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 728,
          height: 90,
          fill: TESCO_RED,
          selectable: false,
          evented: false,
        },
        {
          type: 'i-text',
          left: 30,
          top: 25,
          text: 'BIG SALE',
          fontSize: 36,
          fontFamily: 'Poppins',
          fontWeight: '800',
          fill: WHITE,
        },
        {
          type: 'i-text',
          left: 220,
          top: 20,
          text: 'Up to',
          fontSize: 16,
          fontFamily: 'Poppins',
          fill: WHITE,
        },
        {
          type: 'i-text',
          left: 220,
          top: 38,
          text: '50% OFF',
          fontSize: 32,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: '#FFD700',
        },
        {
          type: 'i-text',
          left: 400,
          top: 35,
          text: 'Selected items • Limited time only',
          fontSize: 14,
          fontFamily: 'Poppins',
          fill: WHITE,
        },
        {
          type: 'rect',
          left: 590,
          top: 25,
          width: 120,
          height: 40,
          fill: WHITE,
          rx: 20,
          ry: 20,
        },
        {
          type: 'i-text',
          left: 615,
          top: 35,
          text: 'Shop Sale',
          fontSize: 14,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: TESCO_RED,
        },
      ],
      background: TESCO_RED,
    },
  },
  {
    id: 'clubcard-promo-leaderboard',
    name: 'Clubcard Promo',
    category: 'clubcard',
    description: 'Clubcard exclusive pricing template',
    width: 728,
    height: 90,
    canvasJSON: {
      version: '6.0.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 728,
          height: 90,
          fill: TESCO_BLUE,
          selectable: false,
          evented: false,
        },
        {
          type: 'rect',
          left: 15,
          top: 15,
          width: 120,
          height: 60,
          fill: WHITE,
          rx: 5,
          ry: 5,
        },
        {
          type: 'i-text',
          left: 35,
          top: 25,
          text: 'Clubcard',
          fontSize: 16,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: TESCO_BLUE,
        },
        {
          type: 'i-text',
          left: 40,
          top: 48,
          text: 'PRICE',
          fontSize: 14,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: TESCO_RED,
        },
        {
          type: 'i-text',
          left: 160,
          top: 15,
          text: 'EXCLUSIVE MEMBER DEAL',
          fontSize: 12,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: '#FFD700',
        },
        {
          type: 'i-text',
          left: 160,
          top: 35,
          text: 'Product Name - Was £X.XX',
          fontSize: 20,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: WHITE,
        },
        {
          type: 'i-text',
          left: 160,
          top: 60,
          text: 'Now only £X.XX with Clubcard',
          fontSize: 14,
          fontFamily: 'Poppins',
          fill: WHITE,
        },
        {
          type: 'rect',
          left: 590,
          top: 25,
          width: 120,
          height: 40,
          fill: WHITE,
          rx: 20,
          ry: 20,
        },
        {
          type: 'i-text',
          left: 608,
          top: 35,
          text: 'Get Deal',
          fontSize: 14,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: TESCO_BLUE,
        },
      ],
      background: TESCO_BLUE,
    },
  },
  {
    id: 'seasonal-offer-leaderboard',
    name: 'Seasonal Offer',
    category: 'seasonal',
    description: 'Seasonal promotions and holidays',
    width: 728,
    height: 90,
    canvasJSON: {
      version: '6.0.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 728,
          height: 90,
          fill: '#1a472a', // Deep green
          selectable: false,
          evented: false,
        },
        {
          type: 'i-text',
          left: 30,
          top: 18,
          text: '🎄',
          fontSize: 40,
        },
        {
          type: 'i-text',
          left: 90,
          top: 15,
          text: 'FESTIVE DEALS',
          fontSize: 14,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: '#FFD700',
        },
        {
          type: 'i-text',
          left: 90,
          top: 35,
          text: 'Make Christmas Special',
          fontSize: 24,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: WHITE,
        },
        {
          type: 'i-text',
          left: 90,
          top: 65,
          text: 'Everything you need for the perfect celebration',
          fontSize: 12,
          fontFamily: 'Poppins',
          fill: WHITE,
        },
        {
          type: 'rect',
          left: 560,
          top: 25,
          width: 150,
          height: 40,
          fill: TESCO_RED,
          rx: 20,
          ry: 20,
        },
        {
          type: 'i-text',
          left: 580,
          top: 35,
          text: 'Shop Festive',
          fontSize: 14,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: WHITE,
        },
      ],
      background: '#1a472a',
    },
  },
  {
    id: 'new-arrival-leaderboard',
    name: 'New Arrival',
    category: 'product',
    description: 'Announce new products',
    width: 728,
    height: 90,
    canvasJSON: {
      version: '6.0.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 728,
          height: 90,
          fill: LIGHT_GRAY,
          selectable: false,
          evented: false,
        },
        {
          type: 'rect',
          left: 15,
          top: 15,
          width: 60,
          height: 60,
          fill: TESCO_BLUE,
          rx: 30,
          ry: 30,
        },
        {
          type: 'i-text',
          left: 28,
          top: 30,
          text: 'NEW',
          fontSize: 14,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: WHITE,
        },
        {
          type: 'i-text',
          left: 95,
          top: 15,
          text: 'JUST ARRIVED',
          fontSize: 12,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: TESCO_BLUE,
        },
        {
          type: 'i-text',
          left: 95,
          top: 32,
          text: 'Discover Our Latest Products',
          fontSize: 22,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: BLACK,
        },
        {
          type: 'i-text',
          left: 95,
          top: 60,
          text: 'Fresh arrivals for every taste',
          fontSize: 12,
          fontFamily: 'Poppins',
          fill: '#666666',
        },
        {
          type: 'rect',
          left: 560,
          top: 25,
          width: 150,
          height: 40,
          fill: TESCO_BLUE,
          rx: 20,
          ry: 20,
        },
        {
          type: 'i-text',
          left: 588,
          top: 35,
          text: 'Explore Now',
          fontSize: 14,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: WHITE,
        },
      ],
      background: LIGHT_GRAY,
    },
  },
  {
    id: 'product-showcase-rectangle',
    name: 'Product Card',
    category: 'product',
    description: 'Medium rectangle product showcase',
    width: 300,
    height: 250,
    canvasJSON: {
      version: '6.0.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 300,
          height: 250,
          fill: WHITE,
          selectable: false,
          evented: false,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 300,
          height: 140,
          fill: LIGHT_GRAY,
        },
        {
          type: 'i-text',
          left: 15,
          top: 155,
          text: 'PRODUCT NAME',
          fontSize: 16,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: BLACK,
        },
        {
          type: 'i-text',
          left: 15,
          top: 180,
          text: 'Great value everyday',
          fontSize: 12,
          fontFamily: 'Poppins',
          fill: '#666666',
        },
        {
          type: 'i-text',
          left: 15,
          top: 210,
          text: '£X.XX',
          fontSize: 24,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: TESCO_RED,
        },
        {
          type: 'rect',
          left: 180,
          top: 200,
          width: 105,
          height: 36,
          fill: TESCO_BLUE,
          rx: 18,
          ry: 18,
        },
        {
          type: 'i-text',
          left: 198,
          top: 208,
          text: 'Add to Basket',
          fontSize: 11,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: WHITE,
        },
      ],
      background: WHITE,
    },
  },
  {
    id: 'multi-buy-rectangle',
    name: 'Multi-Buy Deal',
    category: 'promotion',
    description: 'Multi-buy offer template',
    width: 300,
    height: 250,
    canvasJSON: {
      version: '6.0.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 300,
          height: 250,
          fill: TESCO_RED,
          selectable: false,
          evented: false,
        },
        {
          type: 'rect',
          left: 20,
          top: 20,
          width: 260,
          height: 80,
          fill: WHITE,
          rx: 10,
          ry: 10,
        },
        {
          type: 'i-text',
          left: 60,
          top: 35,
          text: 'BUY 2 FOR',
          fontSize: 20,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: BLACK,
        },
        {
          type: 'i-text',
          left: 80,
          top: 60,
          text: '£X.XX',
          fontSize: 28,
          fontFamily: 'Poppins',
          fontWeight: '800',
          fill: TESCO_RED,
        },
        {
          type: 'i-text',
          left: 30,
          top: 120,
          text: 'Product Name',
          fontSize: 22,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: WHITE,
        },
        {
          type: 'i-text',
          left: 30,
          top: 150,
          text: 'Mix & Match Available',
          fontSize: 14,
          fontFamily: 'Poppins',
          fill: WHITE,
        },
        {
          type: 'rect',
          left: 60,
          top: 190,
          width: 180,
          height: 44,
          fill: WHITE,
          rx: 22,
          ry: 22,
        },
        {
          type: 'i-text',
          left: 105,
          top: 202,
          text: 'Shop Now',
          fontSize: 16,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: TESCO_RED,
        },
      ],
      background: TESCO_RED,
    },
  },
  {
    id: 'brand-awareness-billboard',
    name: 'Brand Awareness',
    category: 'awareness',
    description: 'Large billboard for brand messaging',
    width: 970,
    height: 250,
    canvasJSON: {
      version: '6.0.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 970,
          height: 250,
          fill: WHITE,
          selectable: false,
          evented: false,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 400,
          height: 250,
          fill: TESCO_BLUE,
        },
        {
          type: 'i-text',
          left: 30,
          top: 40,
          text: 'TESCO',
          fontSize: 32,
          fontFamily: 'Poppins',
          fontWeight: '800',
          fill: WHITE,
        },
        {
          type: 'i-text',
          left: 30,
          top: 90,
          text: 'Every Little Helps',
          fontSize: 28,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: WHITE,
        },
        {
          type: 'i-text',
          left: 30,
          top: 140,
          text: 'Quality products at\ngreat prices, every day.',
          fontSize: 16,
          fontFamily: 'Poppins',
          fill: WHITE,
          lineHeight: 1.4,
        },
        {
          type: 'rect',
          left: 30,
          top: 195,
          width: 140,
          height: 40,
          fill: TESCO_RED,
          rx: 20,
          ry: 20,
        },
        {
          type: 'i-text',
          left: 55,
          top: 205,
          text: 'Shop Now',
          fontSize: 14,
          fontFamily: 'Poppins',
          fontWeight: 'bold',
          fill: WHITE,
        },
        {
          type: 'rect',
          left: 450,
          top: 30,
          width: 490,
          height: 190,
          fill: LIGHT_GRAY,
          rx: 10,
          ry: 10,
        },
        {
          type: 'i-text',
          left: 650,
          top: 110,
          text: '[Product Image]',
          fontSize: 16,
          fontFamily: 'Poppins',
          fill: '#999999',
        },
      ],
      background: WHITE,
    },
  },
];

// Get templates by category
export function getTemplatesByCategory(category: AdTemplate['category']): AdTemplate[] {
  return adTemplates.filter(t => t.category === category);
}

// Get templates by size
export function getTemplatesBySize(width: number, height: number): AdTemplate[] {
  return adTemplates.filter(t => t.width === width && t.height === height);
}

// Get all categories
export function getCategories(): AdTemplate['category'][] {
  return ['promotion', 'product', 'seasonal', 'clubcard', 'awareness'];
}

// Export singleton
export default adTemplates;
